extern	void	CHROUT	(char d);
extern	char	CHRIN	();
extern	void	PRNTLN	(const char * s);
extern	void	PRNT	(const char * s);
extern	void	PRNL	();
extern	void	SETBNK	(char d);
extern	char	GETBNK	();
extern	void	SNINIT	();
extern	void	SNWRT	(char d);
extern	void	SHDLY	();
extern	void	RST	();
extern	char	KBINPUT	();
extern	char	KBGET	();
extern	char	KBSCAN	();
extern	void	KBINIT	();
extern	char	INPUT	();
extern	void	DLY	();
extern	void	INTEN	();
extern	void	INTDI	();
extern	void	GET_INTERRUPT	();
extern	char	ACIA_SCAN	();
extern	void	SPI_INIT	();
extern	void	SPI_WRITE	(char d);
extern	char	ACIA_IN	();
extern	void	ACIAINIT	();
extern	void	VERAINIT (char c);
extern  void    VERARESET();
extern  void    VERAL0ENABLE(  );
extern  void    VERAL1ENABLE();
extern  void    VERAL0DISABLE();
extern  void    VERAL1DISABLE();
